"""identity and system

Revision ID: 0001
Revises: 
Create Date: 2026-09-04 00:33:02.736965

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companysettings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('owner', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('unit', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('costcategory',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scope', sa.Enum('PROJECT', 'COMPANY', name='costcategoryscope'), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_costcategory_scope'), 'costcategory', ['scope'], unique=False)
    op.create_table('department',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('head_user_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_department_head_user_id'), 'department', ['head_user_id'], unique=False)
    op.create_table('payprofile',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('role_title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('daily_rate', sa.Integer(), nullable=False),
    sa.Column('allowances', sa.JSON(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_title')
    )
    op.create_table('user',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'DIRECTOR', 'DEPARTMENT_HEAD', 'EMPLOYEE', name='role'), nullable=False),
    sa.Column('department_id', sa.Uuid(), nullable=True),
    sa.Column('failed_login_count', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('last_active_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_department_id'), 'user', ['department_id'], unique=False)
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('employee',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('hire_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'ON_LEAVE', name='employeestatus'), nullable=False),
    sa.Column('pay_profile_id', sa.Uuid(), nullable=True),
    sa.Column('daily_rate_override', sa.Integer(), nullable=True),
    sa.Column('allowance_overrides', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['pay_profile_id'], ['payprofile.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_user_id'), 'employee', ['user_id'], unique=True)
    op.create_table('userpermissiongrant',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('permission_group', sa.Enum('PROJECT_CASHBOOK', 'OVERHEAD_ALLOCATE', 'FUNDS', 'DEBTS', 'CONTRACTS_COLLECT', 'WORKDAYS_ENTRY', name='permissiongroup'), nullable=False),
    sa.Column('scope', sa.JSON(), nullable=True),
    sa.Column('granted_by_id', sa.Uuid(), nullable=False),
    sa.Column('granted_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['granted_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_userpermissiongrant_permission_group'), 'userpermissiongrant', ['permission_group'], unique=False)
    op.create_index(op.f('ix_userpermissiongrant_user_id'), 'userpermissiongrant', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_userpermissiongrant_user_id'), table_name='userpermissiongrant')
    op.drop_index(op.f('ix_userpermissiongrant_permission_group'), table_name='userpermissiongrant')
    op.drop_table('userpermissiongrant')
    op.drop_index(op.f('ix_employee_user_id'), table_name='employee')
    op.drop_table('employee')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_index(op.f('ix_user_department_id'), table_name='user')
    op.drop_table('user')
    op.drop_table('payprofile')
    op.drop_index(op.f('ix_department_head_user_id'), table_name='department')
    op.drop_table('department')
    op.drop_index(op.f('ix_costcategory_scope'), table_name='costcategory')
    op.drop_table('costcategory')
    op.drop_table('companysettings')
    # ### end Alembic commands ###
    # `op.drop_table` does not drop the Postgres ENUM types backing Enum columns —
    # without this they orphan and collide with `CREATE TYPE` on the next upgrade.
    bind = op.get_bind()
    for enum_name in ('role', 'permissiongroup', 'employeestatus', 'costcategoryscope'):
        sa.Enum(name=enum_name).drop(bind, checkfirst=True)
