"""leads projects tasks workitems activity

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-04 02:05:43.698594

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lead',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('need', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('budget_estimate', sa.Integer(), nullable=True),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'CONSULTING', 'QUOTED', 'CONVERTED', 'REJECTED', name='leadstatus'), nullable=False),
    sa.Column('converted_project_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lead_owner_id'), 'lead', ['owner_id'], unique=False)
    op.create_index(op.f('ix_lead_phone'), 'lead', ['phone'], unique=False)
    op.create_index(op.f('ix_lead_status'), 'lead', ['status'], unique=False)
    op.create_table('project',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('client', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sa.Enum('DESIGN', 'CONSTRUCTION', 'TURNKEY', name='projectcategory'), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('area', sa.Float(), nullable=True),
    sa.Column('budget', sa.Integer(), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('stage_progress', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('PLANNING', 'IN_PROGRESS', 'AWAITING_FEEDBACK', 'COMPLETED', name='projectstatus'), nullable=False),
    sa.Column('lead_id', sa.Uuid(), nullable=True),
    sa.Column('manager_id', sa.Uuid(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['lead.id'], ),
    sa.ForeignKeyConstraint(['manager_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_category'), 'project', ['category'], unique=False)
    op.create_index(op.f('ix_project_code'), 'project', ['code'], unique=True)
    op.create_index(op.f('ix_project_status'), 'project', ['status'], unique=False)
    # `lead` and `project` FK each other — `project` table must exist before this
    # constraint can be added (see Lead.converted_project_id `use_alter=True`).
    op.create_foreign_key(
        'fk_lead_converted_project', 'lead', 'project', ['converted_project_id'], ['id']
    )
    op.create_table('activity',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('icon', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_created_at'), 'activity', ['created_at'], unique=False)
    op.create_index(op.f('ix_activity_project_id'), 'activity', ['project_id'], unique=False)
    op.create_index(op.f('ix_activity_user_id'), 'activity', ['user_id'], unique=False)
    op.create_table('projectdepartmenthead',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('department_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projectdepartmenthead_department_id'), 'projectdepartmenthead', ['department_id'], unique=False)
    op.create_index(op.f('ix_projectdepartmenthead_project_id'), 'projectdepartmenthead', ['project_id'], unique=False)
    op.create_index(op.f('ix_projectdepartmenthead_user_id'), 'projectdepartmenthead', ['user_id'], unique=False)
    op.create_table('task',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('department_id', sa.Uuid(), nullable=False),
    sa.Column('parent_task_id', sa.Uuid(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='taskpriority'), nullable=False),
    sa.Column('status', sa.Enum('TODO', 'DOING', 'DONE', name='taskstatus'), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('assignee_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assignee_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], ),
    sa.ForeignKeyConstraint(['parent_task_id'], ['task.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_assignee_id'), 'task', ['assignee_id'], unique=False)
    op.create_index(op.f('ix_task_department_id'), 'task', ['department_id'], unique=False)
    op.create_index(op.f('ix_task_parent_task_id'), 'task', ['parent_task_id'], unique=False)
    op.create_index(op.f('ix_task_project_id'), 'task', ['project_id'], unique=False)
    op.create_index(op.f('ix_task_status'), 'task', ['status'], unique=False)
    op.create_table('workitem',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('department_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('unit', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit_price', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('NOT_STARTED', 'IN_PROGRESS', 'DONE', name='workitemstatus'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workitem_department_id'), 'workitem', ['department_id'], unique=False)
    op.create_index(op.f('ix_workitem_project_id'), 'workitem', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workitem_project_id'), table_name='workitem')
    op.drop_index(op.f('ix_workitem_department_id'), table_name='workitem')
    op.drop_table('workitem')
    op.drop_index(op.f('ix_task_status'), table_name='task')
    op.drop_index(op.f('ix_task_project_id'), table_name='task')
    op.drop_index(op.f('ix_task_parent_task_id'), table_name='task')
    op.drop_index(op.f('ix_task_department_id'), table_name='task')
    op.drop_index(op.f('ix_task_assignee_id'), table_name='task')
    op.drop_table('task')
    op.drop_index(op.f('ix_projectdepartmenthead_user_id'), table_name='projectdepartmenthead')
    op.drop_index(op.f('ix_projectdepartmenthead_project_id'), table_name='projectdepartmenthead')
    op.drop_index(op.f('ix_projectdepartmenthead_department_id'), table_name='projectdepartmenthead')
    op.drop_table('projectdepartmenthead')
    op.drop_index(op.f('ix_activity_user_id'), table_name='activity')
    op.drop_index(op.f('ix_activity_project_id'), table_name='activity')
    op.drop_index(op.f('ix_activity_created_at'), table_name='activity')
    op.drop_table('activity')
    op.drop_constraint('fk_lead_converted_project', 'lead', type_='foreignkey')
    op.drop_index(op.f('ix_project_status'), table_name='project')
    op.drop_index(op.f('ix_project_code'), table_name='project')
    op.drop_index(op.f('ix_project_category'), table_name='project')
    op.drop_table('project')
    op.drop_index(op.f('ix_lead_status'), table_name='lead')
    op.drop_index(op.f('ix_lead_phone'), table_name='lead')
    op.drop_index(op.f('ix_lead_owner_id'), table_name='lead')
    op.drop_table('lead')
    # ### end Alembic commands ###
    # `op.drop_table` does not drop the Postgres ENUM types backing Enum columns —
    # without this they orphan and collide with `CREATE TYPE` on the next upgrade.
    bind = op.get_bind()
    for enum_name in (
        'leadstatus',
        'projectcategory',
        'projectstatus',
        'taskpriority',
        'taskstatus',
        'workitemstatus',
    ):
        sa.Enum(name=enum_name).drop(bind, checkfirst=True)
