"""budget finance contracts overhead

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-04 20:34:49.626670

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '0003'
down_revision = '0002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fundaccount',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sa.Enum('CASH', 'BANK', name='fundtype'), nullable=False),
    sa.Column('balance', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('overheadcost',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('cost_category_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('month', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['cost_category_id'], ['costcategory.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_overheadcost_month'), 'overheadcost', ['month'], unique=False)
    op.create_table('cashledgerentry',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('fund_account_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('inflow', sa.Integer(), nullable=False),
    sa.Column('outflow', sa.Integer(), nullable=False),
    sa.Column('source_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('recorded_by_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['fund_account_id'], ['fundaccount.id'], ),
    sa.ForeignKeyConstraint(['recorded_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cashledgerentry_fund_account_id'), 'cashledgerentry', ['fund_account_id'], unique=False)
    op.create_index(op.f('ix_cashledgerentry_source_type'), 'cashledgerentry', ['source_type'], unique=False)
    op.create_table('budgetestimate',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING', 'APPROVED', name='budgetestimatestatus'), nullable=False),
    sa.Column('approved_by_id', sa.Uuid(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_budgetestimate_project_id'), 'budgetestimate', ['project_id'], unique=False)
    op.create_index(op.f('ix_budgetestimate_status'), 'budgetestimate', ['status'], unique=False)
    op.create_table('contract',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sa.Enum('DESIGN', 'CONSTRUCTION', 'TURNKEY', name='projectcategory'), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('signed_date', sa.Date(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'EXPIRING_SOON', 'LIQUIDATED', 'SETTLED', name='contractstatus'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contract_code'), 'contract', ['code'], unique=True)
    op.create_index(op.f('ix_contract_project_id'), 'contract', ['project_id'], unique=False)
    op.create_index(op.f('ix_contract_status'), 'contract', ['status'], unique=False)
    op.create_table('overheadallocation',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('month', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('revenue_share', sa.Float(), nullable=False),
    sa.Column('allocated_amount', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('month', 'project_id', name='uq_overhead_allocation_month_project')
    )
    op.create_index(op.f('ix_overheadallocation_month'), 'overheadallocation', ['month'], unique=False)
    op.create_index(op.f('ix_overheadallocation_project_id'), 'overheadallocation', ['project_id'], unique=False)
    op.create_table('payable',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('vendor_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cost_category_id', sa.Uuid(), nullable=False),
    sa.Column('total_amount', sa.Integer(), nullable=False),
    sa.Column('paid_amount', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'OVERDUE', 'SETTLED', name='payablestatus'), nullable=False),
    sa.ForeignKeyConstraint(['cost_category_id'], ['costcategory.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payable_project_id'), 'payable', ['project_id'], unique=False)
    op.create_index(op.f('ix_payable_status'), 'payable', ['status'], unique=False)
    op.create_table('budgetestimateline',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('budget_estimate_id', sa.Uuid(), nullable=False),
    sa.Column('cost_category_id', sa.Uuid(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('unit', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit_price', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['budget_estimate_id'], ['budgetestimate.id'], ),
    sa.ForeignKeyConstraint(['cost_category_id'], ['costcategory.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_budgetestimateline_budget_estimate_id'), 'budgetestimateline', ['budget_estimate_id'], unique=False)
    op.create_table('contractmilestone',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('contract_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('condition', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ratio', sa.Float(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('paid_amount', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PARTIALLY_PAID', 'PAID', 'OVERDUE', 'RETAINED', name='milestonestatus'), nullable=False),
    sa.Column('is_retention', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contract.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contractmilestone_contract_id'), 'contractmilestone', ['contract_id'], unique=False)
    op.create_index(op.f('ix_contractmilestone_status'), 'contractmilestone', ['status'], unique=False)
    op.create_table('projectcost',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('cost_category_id', sa.Uuid(), nullable=False),
    sa.Column('work_item_id', sa.Uuid(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('recorded_by_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cost_category_id'], ['costcategory.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['recorded_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['work_item_id'], ['workitem.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projectcost_cost_category_id'), 'projectcost', ['cost_category_id'], unique=False)
    op.create_index(op.f('ix_projectcost_project_id'), 'projectcost', ['project_id'], unique=False)
    op.create_table('payment',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('contract_milestone_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('fund_account_id', sa.Uuid(), nullable=False),
    sa.Column('recorded_by_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['contract_milestone_id'], ['contractmilestone.id'], ),
    sa.ForeignKeyConstraint(['fund_account_id'], ['fundaccount.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['recorded_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_contract_milestone_id'), 'payment', ['contract_milestone_id'], unique=False)
    op.create_index(op.f('ix_payment_project_id'), 'payment', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_project_id'), table_name='payment')
    op.drop_index(op.f('ix_payment_contract_milestone_id'), table_name='payment')
    op.drop_table('payment')
    op.drop_index(op.f('ix_projectcost_project_id'), table_name='projectcost')
    op.drop_index(op.f('ix_projectcost_cost_category_id'), table_name='projectcost')
    op.drop_table('projectcost')
    op.drop_index(op.f('ix_contractmilestone_status'), table_name='contractmilestone')
    op.drop_index(op.f('ix_contractmilestone_contract_id'), table_name='contractmilestone')
    op.drop_table('contractmilestone')
    op.drop_index(op.f('ix_budgetestimateline_budget_estimate_id'), table_name='budgetestimateline')
    op.drop_table('budgetestimateline')
    op.drop_index(op.f('ix_payable_status'), table_name='payable')
    op.drop_index(op.f('ix_payable_project_id'), table_name='payable')
    op.drop_table('payable')
    op.drop_index(op.f('ix_overheadallocation_project_id'), table_name='overheadallocation')
    op.drop_index(op.f('ix_overheadallocation_month'), table_name='overheadallocation')
    op.drop_table('overheadallocation')
    op.drop_index(op.f('ix_contract_status'), table_name='contract')
    op.drop_index(op.f('ix_contract_project_id'), table_name='contract')
    op.drop_index(op.f('ix_contract_code'), table_name='contract')
    op.drop_table('contract')
    op.drop_index(op.f('ix_budgetestimate_status'), table_name='budgetestimate')
    op.drop_index(op.f('ix_budgetestimate_project_id'), table_name='budgetestimate')
    op.drop_table('budgetestimate')
    op.drop_index(op.f('ix_cashledgerentry_source_type'), table_name='cashledgerentry')
    op.drop_index(op.f('ix_cashledgerentry_fund_account_id'), table_name='cashledgerentry')
    op.drop_table('cashledgerentry')
    op.drop_index(op.f('ix_overheadcost_month'), table_name='overheadcost')
    op.drop_table('overheadcost')
    op.drop_table('fundaccount')
    # ### end Alembic commands ###
    # `op.drop_table` does not drop the Postgres ENUM types backing Enum columns —
    # without this they orphan and collide with `CREATE TYPE` on the next upgrade.
    bind = op.get_bind()
    # `projectcategory` KHÔNG drop ở đây — do migration 0002 tạo (dùng chung với
    # Project.category, bảng đó vẫn còn tồn tại lúc downgrade 0003 chạy); 0002 tự
    # drop nó trong downgrade của chính nó, sau khi bảng project đã bị xoá.
    for enum_name in (
        'fundtype',
        'budgetestimatestatus',
        'contractstatus',
        'payablestatus',
        'milestonestatus',
    ):
        sa.Enum(name=enum_name).drop(bind, checkfirst=True)
