"""workdays payroll files notifications bigint fix

Revision ID: 0004
Revises: 0003
Create Date: 2026-09-04 21:25:43.315344

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '0004'
down_revision = '0003'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_created_at'), 'notification', ['created_at'], unique=False)
    op.create_index(op.f('ix_notification_read'), 'notification', ['read'], unique=False)
    op.create_index(op.f('ix_notification_user_id'), 'notification', ['user_id'], unique=False)
    op.create_table('monthlyworkdays',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('employee_id', sa.Uuid(), nullable=False),
    sa.Column('month', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('actual_days', sa.Float(), nullable=False),
    sa.Column('entered_by_id', sa.Uuid(), nullable=False),
    sa.Column('locked_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['entered_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'month', name='uq_workdays_employee_month')
    )
    op.create_index(op.f('ix_monthlyworkdays_employee_id'), 'monthlyworkdays', ['employee_id'], unique=False)
    op.create_index(op.f('ix_monthlyworkdays_month'), 'monthlyworkdays', ['month'], unique=False)
    op.create_table('payrollrecord',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('employee_id', sa.Uuid(), nullable=False),
    sa.Column('month', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('daily_rate', sa.BigInteger(), nullable=False),
    sa.Column('actual_days', sa.Float(), nullable=False),
    sa.Column('day_wage', sa.BigInteger(), nullable=False),
    sa.Column('allowances', sa.JSON(), nullable=True),
    sa.Column('net_pay', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('UNPAID', 'PAID', name='payrollstatus'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'month', name='uq_payroll_employee_month')
    )
    op.create_index(op.f('ix_payrollrecord_employee_id'), 'payrollrecord', ['employee_id'], unique=False)
    op.create_index(op.f('ix_payrollrecord_month'), 'payrollrecord', ['month'], unique=False)
    op.create_index(op.f('ix_payrollrecord_status'), 'payrollrecord', ['status'], unique=False)
    op.create_table('fileasset',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('storage_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('uploaded_by_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fileasset_project_id'), 'fileasset', ['project_id'], unique=False)
    op.alter_column('budgetestimateline', 'unit_price',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('budgetestimateline', 'amount',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('cashledgerentry', 'inflow',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('cashledgerentry', 'outflow',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('contract', 'value',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('contractmilestone', 'amount',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('contractmilestone', 'paid_amount',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('employee', 'daily_rate_override',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.alter_column('fundaccount', 'balance',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('lead', 'budget_estimate',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.alter_column('overheadallocation', 'allocated_amount',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('overheadcost', 'amount',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('payable', 'total_amount',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('payable', 'paid_amount',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('payment', 'amount',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('payprofile', 'daily_rate',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('project', 'budget',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.alter_column('projectcost', 'amount',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('workitem', 'unit_price',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('workitem', 'amount',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workitem', 'amount',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('workitem', 'unit_price',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('projectcost', 'amount',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('project', 'budget',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('payprofile', 'daily_rate',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('payment', 'amount',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('payable', 'paid_amount',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('payable', 'total_amount',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('overheadcost', 'amount',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('overheadallocation', 'allocated_amount',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('lead', 'budget_estimate',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('fundaccount', 'balance',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('employee', 'daily_rate_override',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('contractmilestone', 'paid_amount',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('contractmilestone', 'amount',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('contract', 'value',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('cashledgerentry', 'outflow',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('cashledgerentry', 'inflow',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('budgetestimateline', 'amount',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('budgetestimateline', 'unit_price',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_index(op.f('ix_fileasset_project_id'), table_name='fileasset')
    op.drop_table('fileasset')
    op.drop_index(op.f('ix_payrollrecord_status'), table_name='payrollrecord')
    op.drop_index(op.f('ix_payrollrecord_month'), table_name='payrollrecord')
    op.drop_index(op.f('ix_payrollrecord_employee_id'), table_name='payrollrecord')
    op.drop_table('payrollrecord')
    op.drop_index(op.f('ix_monthlyworkdays_month'), table_name='monthlyworkdays')
    op.drop_index(op.f('ix_monthlyworkdays_employee_id'), table_name='monthlyworkdays')
    op.drop_table('monthlyworkdays')
    op.drop_index(op.f('ix_notification_user_id'), table_name='notification')
    op.drop_index(op.f('ix_notification_read'), table_name='notification')
    op.drop_index(op.f('ix_notification_created_at'), table_name='notification')
    op.drop_table('notification')
    # ### end Alembic commands ###
    # `op.drop_table` does not drop the Postgres ENUM types backing Enum columns —
    # without this they orphan and collide with `CREATE TYPE` on the next upgrade.
    sa.Enum(name='payrollstatus').drop(op.get_bind(), checkfirst=True)
